version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/app/common/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/app/auth/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'docker'
    directory: '/app/auth/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/app/client/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'docker'
    directory: '/app/client/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/app/tickets/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'docker'
    directory: '/app/tickets/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/app/nats-test/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/app/orders/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'docker'
    directory: '/app/orders/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/app/expiration/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'docker'
    directory: '/app/expiration/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/app/payments/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'docker'
    directory: '/app/payments/'
    schedule:
      interval: 'monthly'
