# name: deploy-manifests

# on:
#   push:
#     branches:
#       - master
#     paths:
#       - 'k8s/**'

# jobs:
#   build:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - uses: digitalocean/actions-doctl@v2
#         with:
#           token: ${{secretes.DIGITAL_OCEAN_ACCESS_TOKEN}}
#       - run: doctl kubernetes cluster kubeconfig save <kubernetes_cluster_name>
#       - run: kubectl apply -f k8s/common && kubectl apply -f k8s/prod
